sudo : required 
services:
    - docker

before_install:
    - docker build -t jimmyyouhei/react -f ./client/Dockerfile.dev ./client

script: 
    - docker run -e CI=true jimmyyouhei/react npm test

after-success: 
    - docker build -t jimmyyouhei/client ./client
    - docker build -t jimmyyouhei/nginx ./nginx
    - docker build -t jimmyyouhei/server ./server
    - docker build -t jimmyyouhei/worker ./worker

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push jimmyyouhei/client
    - docker push jimmyyouhei/nginx
    - docker push jimmyyouhei/server
    - docker push jimmyyouhei/worker
    

